services:
  report-service:
    container_name: report-service
    build: .
    image: report-service:latest
    pull_policy: never
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    restart: unless-stopped
